/*
 * Sūrah Yā-Sīn (36), 83 verses.
 * Arabic: Tanzil Project Uthmani text (https://tanzil.net), used verbatim. The basmalah is kept separate from verse 1.
 * English: Marmaduke Pickthall, The Meaning of the Glorious Koran (1930), public domain.
 * Both taken from the alquran.cloud editions quran-uthmani and en.pickthall (via github.com/AbdullahGhanem/quran-database),
 *   the same source as the Kahf app's text: that copy reproduces all 110 verses of al-Kahf in the Kahf app exactly.
 */
const SURAH = {
  number: 36,
  name_ar: "سورة يس",
  name_en: "Sūrah Yā-Sīn",
  basmalah_ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
  basmalah_en: "In the name of Allah, the Beneficent, the Merciful.",
  verses: [
    {"n": 1, "ar": "يسٓ", "en": "Ya Sin."},
    {"n": 2, "ar": "وَٱلْقُرْءَانِ ٱلْحَكِيمِ", "en": "By the wise Qur'an,"},
    {"n": 3, "ar": "إِنَّكَ لَمِنَ ٱلْمُرْسَلِينَ", "en": "Lo! thou art of those sent"},
    {"n": 4, "ar": "عَلَىٰ صِرَٰطٍۢ مُّسْتَقِيمٍۢ", "en": "On a straight path,"},
    {"n": 5, "ar": "تَنزِيلَ ٱلْعَزِيزِ ٱلرَّحِيمِ", "en": "A revelation of the Mighty, the Merciful,"},
    {"n": 6, "ar": "لِتُنذِرَ قَوْمًۭا مَّآ أُنذِرَ ءَابَآؤُهُمْ فَهُمْ غَٰفِلُونَ", "en": "That thou mayst warn a folk whose fathers were not warned, so they are heedless."},
    {"n": 7, "ar": "لَقَدْ حَقَّ ٱلْقَوْلُ عَلَىٰٓ أَكْثَرِهِمْ فَهُمْ لَا يُؤْمِنُونَ", "en": "Already hath the judgment, (for their infidelity) proved true of most of them, for they believe not."},
    {"n": 8, "ar": "إِنَّا جَعَلْنَا فِىٓ أَعْنَٰقِهِمْ أَغْلَٰلًۭا فَهِىَ إِلَى ٱلْأَذْقَانِ فَهُم مُّقْمَحُونَ", "en": "Lo! We have put on their necks carcans reaching unto the chins, so that they are made stiff-necked."},
    {"n": 9, "ar": "وَجَعَلْنَا مِنۢ بَيْنِ أَيْدِيهِمْ سَدًّۭا وَمِنْ خَلْفِهِمْ سَدًّۭا فَأَغْشَيْنَٰهُمْ فَهُمْ لَا يُبْصِرُونَ", "en": "And We have set a bar before them and a bar behind them, and (thus) have covered them so that they see not."},
    {"n": 10, "ar": "وَسَوَآءٌ عَلَيْهِمْ ءَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ", "en": "Whether thou warn them or thou warn them not, it is alike for them, for they believe not."},
    {"n": 11, "ar": "إِنَّمَا تُنذِرُ مَنِ ٱتَّبَعَ ٱلذِّكْرَ وَخَشِىَ ٱلرَّحْمَٰنَ بِٱلْغَيْبِ ۖ فَبَشِّرْهُ بِمَغْفِرَةٍۢ وَأَجْرٍۢ كَرِيمٍ", "en": "Thou warnest only him who followeth the Reminder and feareth the Beneficent in secret. To him bear tidings of forgiveness and a rich reward."},
    {"n": 12, "ar": "إِنَّا نَحْنُ نُحْىِ ٱلْمَوْتَىٰ وَنَكْتُبُ مَا قَدَّمُوا۟ وَءَاثَٰرَهُمْ ۚ وَكُلَّ شَىْءٍ أَحْصَيْنَٰهُ فِىٓ إِمَامٍۢ مُّبِينٍۢ", "en": "Lo! We it is Who bring the dead to life. We record that which they send before (them, and their footprints. And all things We have kept in a clear Register."},
    {"n": 13, "ar": "وَٱضْرِبْ لَهُم مَّثَلًا أَصْحَٰبَ ٱلْقَرْيَةِ إِذْ جَآءَهَا ٱلْمُرْسَلُونَ", "en": "Coin for them a similitude: The people of the city when those sent (from Allah) came unto them;"},
    {"n": 14, "ar": "إِذْ أَرْسَلْنَآ إِلَيْهِمُ ٱثْنَيْنِ فَكَذَّبُوهُمَا فَعَزَّزْنَا بِثَالِثٍۢ فَقَالُوٓا۟ إِنَّآ إِلَيْكُم مُّرْسَلُونَ", "en": "When We sent unto them twain, and they denied them both, so We reinforced them with a third, and they said: Lo! we have been sent unto you."},
    {"n": 15, "ar": "قَالُوا۟ مَآ أَنتُمْ إِلَّا بَشَرٌۭ مِّثْلُنَا وَمَآ أَنزَلَ ٱلرَّحْمَٰنُ مِن شَىْءٍ إِنْ أَنتُمْ إِلَّا تَكْذِبُونَ", "en": "They said: Ye are but mortals like unto us. The Beneficent hath naught revealed. Ye do but lie!"},
    {"n": 16, "ar": "قَالُوا۟ رَبُّنَا يَعْلَمُ إِنَّآ إِلَيْكُمْ لَمُرْسَلُونَ", "en": "They answered: Our Lord knoweth that we are indeed sent unto you,"},
    {"n": 17, "ar": "وَمَا عَلَيْنَآ إِلَّا ٱلْبَلَٰغُ ٱلْمُبِينُ", "en": "And our duty is but plain conveyance (of the message)."},
    {"n": 18, "ar": "قَالُوٓا۟ إِنَّا تَطَيَّرْنَا بِكُمْ ۖ لَئِن لَّمْ تَنتَهُوا۟ لَنَرْجُمَنَّكُمْ وَلَيَمَسَّنَّكُم مِّنَّا عَذَابٌ أَلِيمٌۭ", "en": "(The people of the city) said: We augur ill of you. If ye desist not, we shall surely stone you, and grievous torture will befall you at our hands."},
    {"n": 19, "ar": "قَالُوا۟ طَٰٓئِرُكُم مَّعَكُمْ ۚ أَئِن ذُكِّرْتُم ۚ بَلْ أَنتُمْ قَوْمٌۭ مُّسْرِفُونَ", "en": "They said: Your evil augury be with you! Is it because ye are reminded (of the truth)? Nay, but ye are froward folk!"},
    {"n": 20, "ar": "وَجَآءَ مِنْ أَقْصَا ٱلْمَدِينَةِ رَجُلٌۭ يَسْعَىٰ قَالَ يَٰقَوْمِ ٱتَّبِعُوا۟ ٱلْمُرْسَلِينَ", "en": "And there came from the uttermost part of the city a man running. He cried: O my people! Follow those who have been sent!"},
    {"n": 21, "ar": "ٱتَّبِعُوا۟ مَن لَّا يَسْـَٔلُكُمْ أَجْرًۭا وَهُم مُّهْتَدُونَ", "en": "Follow those who ask of you no fee, and who are rightly guided."},
    {"n": 22, "ar": "وَمَا لِىَ لَآ أَعْبُدُ ٱلَّذِى فَطَرَنِى وَإِلَيْهِ تُرْجَعُونَ", "en": "For what cause should I not serve Him Who hath created me, and unto Whom ye will be brought back?"},
    {"n": 23, "ar": "ءَأَتَّخِذُ مِن دُونِهِۦٓ ءَالِهَةً إِن يُرِدْنِ ٱلرَّحْمَٰنُ بِضُرٍّۢ لَّا تُغْنِ عَنِّى شَفَٰعَتُهُمْ شَيْـًۭٔا وَلَا يُنقِذُونِ", "en": "Shall I take (other) gods in place of Him when, if the Beneficent should wish me any harm, their intercession will avail me naught, nor can they save?"},
    {"n": 24, "ar": "إِنِّىٓ إِذًۭا لَّفِى ضَلَٰلٍۢ مُّبِينٍ", "en": "Then truly I should be in error manifest."},
    {"n": 25, "ar": "إِنِّىٓ ءَامَنتُ بِرَبِّكُمْ فَٱسْمَعُونِ", "en": "Lo! I have believed in your Lord, so hear me!"},
    {"n": 26, "ar": "قِيلَ ٱدْخُلِ ٱلْجَنَّةَ ۖ قَالَ يَٰلَيْتَ قَوْمِى يَعْلَمُونَ", "en": "It was said (unto him): Enter paradise. He said: Would that my people knew"},
    {"n": 27, "ar": "بِمَا غَفَرَ لِى رَبِّى وَجَعَلَنِى مِنَ ٱلْمُكْرَمِينَ", "en": "With what (munificence) my Lord hath pardoned me and made me of the honoured ones!"},
    {"n": 28, "ar": "۞ وَمَآ أَنزَلْنَا عَلَىٰ قَوْمِهِۦ مِنۢ بَعْدِهِۦ مِن جُندٍۢ مِّنَ ٱلسَّمَآءِ وَمَا كُنَّا مُنزِلِينَ", "en": "We sent not down against his people after him a host from heaven, nor do We ever send."},
    {"n": 29, "ar": "إِن كَانَتْ إِلَّا صَيْحَةًۭ وَٰحِدَةًۭ فَإِذَا هُمْ خَٰمِدُونَ", "en": "It was but one Shout, and lo! they were extinct."},
    {"n": 30, "ar": "يَٰحَسْرَةً عَلَى ٱلْعِبَادِ ۚ مَا يَأْتِيهِم مِّن رَّسُولٍ إِلَّا كَانُوا۟ بِهِۦ يَسْتَهْزِءُونَ", "en": "Ah, the anguish for the bondmen! Never came there unto them a messenger but they did mock him!"},
    {"n": 31, "ar": "أَلَمْ يَرَوْا۟ كَمْ أَهْلَكْنَا قَبْلَهُم مِّنَ ٱلْقُرُونِ أَنَّهُمْ إِلَيْهِمْ لَا يَرْجِعُونَ", "en": "Have they not seen how many generations We destroyed before them, which indeed returned not unto them;"},
    {"n": 32, "ar": "وَإِن كُلٌّۭ لَّمَّا جَمِيعٌۭ لَّدَيْنَا مُحْضَرُونَ", "en": "But all, without exception, will be brought before Us."},
    {"n": 33, "ar": "وَءَايَةٌۭ لَّهُمُ ٱلْأَرْضُ ٱلْمَيْتَةُ أَحْيَيْنَٰهَا وَأَخْرَجْنَا مِنْهَا حَبًّۭا فَمِنْهُ يَأْكُلُونَ", "en": "A token unto them is the dead earth. We revive it, and We bring forth from it grain so that they eat thereof;"},
    {"n": 34, "ar": "وَجَعَلْنَا فِيهَا جَنَّٰتٍۢ مِّن نَّخِيلٍۢ وَأَعْنَٰبٍۢ وَفَجَّرْنَا فِيهَا مِنَ ٱلْعُيُونِ", "en": "And We have placed therein gardens of the date-palm and grapes, and We have caused springs of water to gush forth therein,"},
    {"n": 35, "ar": "لِيَأْكُلُوا۟ مِن ثَمَرِهِۦ وَمَا عَمِلَتْهُ أَيْدِيهِمْ ۖ أَفَلَا يَشْكُرُونَ", "en": "That they may eat of the fruit thereof, and their hands made it not. Will they not, then, give thanks?"},
    {"n": 36, "ar": "سُبْحَٰنَ ٱلَّذِى خَلَقَ ٱلْأَزْوَٰجَ كُلَّهَا مِمَّا تُنۢبِتُ ٱلْأَرْضُ وَمِنْ أَنفُسِهِمْ وَمِمَّا لَا يَعْلَمُونَ", "en": "Glory be to Him Who created all the sexual pairs, of that which the earth groweth, and of themselves, and of that which they know not!"},
    {"n": 37, "ar": "وَءَايَةٌۭ لَّهُمُ ٱلَّيْلُ نَسْلَخُ مِنْهُ ٱلنَّهَارَ فَإِذَا هُم مُّظْلِمُونَ", "en": "A token unto them is night. We strip it of the day, and lo! they are in darkness."},
    {"n": 38, "ar": "وَٱلشَّمْسُ تَجْرِى لِمُسْتَقَرٍّۢ لَّهَا ۚ ذَٰلِكَ تَقْدِيرُ ٱلْعَزِيزِ ٱلْعَلِيمِ", "en": "And the sun runneth on unto a resting-place for him. That is the measuring of the Mighty, the Wise."},
    {"n": 39, "ar": "وَٱلْقَمَرَ قَدَّرْنَٰهُ مَنَازِلَ حَتَّىٰ عَادَ كَٱلْعُرْجُونِ ٱلْقَدِيمِ", "en": "And for the moon We have appointed mansions till she return like an old shrivelled palm-leaf."},
    {"n": 40, "ar": "لَا ٱلشَّمْسُ يَنۢبَغِى لَهَآ أَن تُدْرِكَ ٱلْقَمَرَ وَلَا ٱلَّيْلُ سَابِقُ ٱلنَّهَارِ ۚ وَكُلٌّۭ فِى فَلَكٍۢ يَسْبَحُونَ", "en": "It is not for the sun to overtake the moon, nor doth the night outstrip the day. They float each in an orbit."},
    {"n": 41, "ar": "وَءَايَةٌۭ لَّهُمْ أَنَّا حَمَلْنَا ذُرِّيَّتَهُمْ فِى ٱلْفُلْكِ ٱلْمَشْحُونِ", "en": "And a token unto them is that We bear their offspring in the laden ship,"},
    {"n": 42, "ar": "وَخَلَقْنَا لَهُم مِّن مِّثْلِهِۦ مَا يَرْكَبُونَ", "en": "And have created for them of the like thereof whereon they ride."},
    {"n": 43, "ar": "وَإِن نَّشَأْ نُغْرِقْهُمْ فَلَا صَرِيخَ لَهُمْ وَلَا هُمْ يُنقَذُونَ", "en": "And if We will, We drown them, and there is no help for them, neither can they be saved;"},
    {"n": 44, "ar": "إِلَّا رَحْمَةًۭ مِّنَّا وَمَتَٰعًا إِلَىٰ حِينٍۢ", "en": "Unless by mercy from Us and as comfort for a while."},
    {"n": 45, "ar": "وَإِذَا قِيلَ لَهُمُ ٱتَّقُوا۟ مَا بَيْنَ أَيْدِيكُمْ وَمَا خَلْفَكُمْ لَعَلَّكُمْ تُرْحَمُونَ", "en": "When it is said unto them: Beware of that which is before you and that which is behind you, that haply ye may find mercy (they are heedless)."},
    {"n": 46, "ar": "وَمَا تَأْتِيهِم مِّنْ ءَايَةٍۢ مِّنْ ءَايَٰتِ رَبِّهِمْ إِلَّا كَانُوا۟ عَنْهَا مُعْرِضِينَ", "en": "Never came a token of the tokens of their Lord to them, but they did turn away from it!"},
    {"n": 47, "ar": "وَإِذَا قِيلَ لَهُمْ أَنفِقُوا۟ مِمَّا رَزَقَكُمُ ٱللَّهُ قَالَ ٱلَّذِينَ كَفَرُوا۟ لِلَّذِينَ ءَامَنُوٓا۟ أَنُطْعِمُ مَن لَّوْ يَشَآءُ ٱللَّهُ أَطْعَمَهُۥٓ إِنْ أَنتُمْ إِلَّا فِى ضَلَٰلٍۢ مُّبِينٍۢ", "en": "And when it is said unto them: Spend of that wherewith Allah hath provided you, those who disbelieve say unto those who believe: Shall we feed those whom Allah, if He willed, would feed? Ye are in naught else than error manifest."},
    {"n": 48, "ar": "وَيَقُولُونَ مَتَىٰ هَٰذَا ٱلْوَعْدُ إِن كُنتُمْ صَٰدِقِينَ", "en": "And they say: When will this promise be fulfilled, if ye are truthful?"},
    {"n": 49, "ar": "مَا يَنظُرُونَ إِلَّا صَيْحَةًۭ وَٰحِدَةًۭ تَأْخُذُهُمْ وَهُمْ يَخِصِّمُونَ", "en": "They await but one Shout, which will surprise them while they are disputing."},
    {"n": 50, "ar": "فَلَا يَسْتَطِيعُونَ تَوْصِيَةًۭ وَلَآ إِلَىٰٓ أَهْلِهِمْ يَرْجِعُونَ", "en": "Then they cannot make bequest, nor can they return to their own folk."},
    {"n": 51, "ar": "وَنُفِخَ فِى ٱلصُّورِ فَإِذَا هُم مِّنَ ٱلْأَجْدَاثِ إِلَىٰ رَبِّهِمْ يَنسِلُونَ", "en": "And the trumpet is blown and lo! from the graves they hie unto their Lord,"},
    {"n": 52, "ar": "قَالُوا۟ يَٰوَيْلَنَا مَنۢ بَعَثَنَا مِن مَّرْقَدِنَا ۜ ۗ هَٰذَا مَا وَعَدَ ٱلرَّحْمَٰنُ وَصَدَقَ ٱلْمُرْسَلُونَ", "en": "Crying: Woe upon us! Who hath raised us from our place of sleep? This is that which the Beneficent did promise, and the messengers spoke truth."},
    {"n": 53, "ar": "إِن كَانَتْ إِلَّا صَيْحَةًۭ وَٰحِدَةًۭ فَإِذَا هُمْ جَمِيعٌۭ لَّدَيْنَا مُحْضَرُونَ", "en": "It is but one Shout, and behold them brought together before Us!"},
    {"n": 54, "ar": "فَٱلْيَوْمَ لَا تُظْلَمُ نَفْسٌۭ شَيْـًۭٔا وَلَا تُجْزَوْنَ إِلَّا مَا كُنتُمْ تَعْمَلُونَ", "en": "This day no soul is wronged in aught; nor are ye requited aught save what ye used to do."},
    {"n": 55, "ar": "إِنَّ أَصْحَٰبَ ٱلْجَنَّةِ ٱلْيَوْمَ فِى شُغُلٍۢ فَٰكِهُونَ", "en": "Lo! those who merit paradise this day are happily employed,"},
    {"n": 56, "ar": "هُمْ وَأَزْوَٰجُهُمْ فِى ظِلَٰلٍ عَلَى ٱلْأَرَآئِكِ مُتَّكِـُٔونَ", "en": "They and their wives, in pleasant shade, on thrones reclining;"},
    {"n": 57, "ar": "لَهُمْ فِيهَا فَٰكِهَةٌۭ وَلَهُم مَّا يَدَّعُونَ", "en": "Theirs the fruit (of their good deeds) and theirs (all) that they ask;"},
    {"n": 58, "ar": "سَلَٰمٌۭ قَوْلًۭا مِّن رَّبٍّۢ رَّحِيمٍۢ", "en": "The word from a Merciful Lord (for them) is: Peace!"},
    {"n": 59, "ar": "وَٱمْتَٰزُوا۟ ٱلْيَوْمَ أَيُّهَا ٱلْمُجْرِمُونَ", "en": "But avaunt ye, O ye guilty, this day!"},
    {"n": 60, "ar": "۞ أَلَمْ أَعْهَدْ إِلَيْكُمْ يَٰبَنِىٓ ءَادَمَ أَن لَّا تَعْبُدُوا۟ ٱلشَّيْطَٰنَ ۖ إِنَّهُۥ لَكُمْ عَدُوٌّۭ مُّبِينٌۭ", "en": "Did I not charge you, O ye sons of Adam, that ye worship not the devil - Lo! he is your open foe! -"},
    {"n": 61, "ar": "وَأَنِ ٱعْبُدُونِى ۚ هَٰذَا صِرَٰطٌۭ مُّسْتَقِيمٌۭ", "en": "But that ye worship Me? That was the right path."},
    {"n": 62, "ar": "وَلَقَدْ أَضَلَّ مِنكُمْ جِبِلًّۭا كَثِيرًا ۖ أَفَلَمْ تَكُونُوا۟ تَعْقِلُونَ", "en": "Yet he hath led astray of you a great multitude. Had ye then no sense?"},
    {"n": 63, "ar": "هَٰذِهِۦ جَهَنَّمُ ٱلَّتِى كُنتُمْ تُوعَدُونَ", "en": "This is hell which ye were promised (if ye followed him)."},
    {"n": 64, "ar": "ٱصْلَوْهَا ٱلْيَوْمَ بِمَا كُنتُمْ تَكْفُرُونَ", "en": "Burn therein this day for that ye disbelieved."},
    {"n": 65, "ar": "ٱلْيَوْمَ نَخْتِمُ عَلَىٰٓ أَفْوَٰهِهِمْ وَتُكَلِّمُنَآ أَيْدِيهِمْ وَتَشْهَدُ أَرْجُلُهُم بِمَا كَانُوا۟ يَكْسِبُونَ", "en": "This day We seal up their mouths, and their hands speak out to Us and their feet bear witness as to what they used to earn."},
    {"n": 66, "ar": "وَلَوْ نَشَآءُ لَطَمَسْنَا عَلَىٰٓ أَعْيُنِهِمْ فَٱسْتَبَقُوا۟ ٱلصِّرَٰطَ فَأَنَّىٰ يُبْصِرُونَ", "en": "And had We willed, We verily could have quenched their eyesight so that they should struggle for the way. Then how could they have seen?"},
    {"n": 67, "ar": "وَلَوْ نَشَآءُ لَمَسَخْنَٰهُمْ عَلَىٰ مَكَانَتِهِمْ فَمَا ٱسْتَطَٰعُوا۟ مُضِيًّۭا وَلَا يَرْجِعُونَ", "en": "And had We willed, We verily could have fixed them in their place, making them powerless to go forward or turn back."},
    {"n": 68, "ar": "وَمَن نُّعَمِّرْهُ نُنَكِّسْهُ فِى ٱلْخَلْقِ ۖ أَفَلَا يَعْقِلُونَ", "en": "He whom we bring unto old age, We reverse him in creation (making him go back to weakness after strength). Have ye then no sense?"},
    {"n": 69, "ar": "وَمَا عَلَّمْنَٰهُ ٱلشِّعْرَ وَمَا يَنۢبَغِى لَهُۥٓ ۚ إِنْ هُوَ إِلَّا ذِكْرٌۭ وَقُرْءَانٌۭ مُّبِينٌۭ", "en": "And We have not taught him (Muhammad) poetry, nor is it meet for him. This is naught else than a Reminder and a Lecture making plain,"},
    {"n": 70, "ar": "لِّيُنذِرَ مَن كَانَ حَيًّۭا وَيَحِقَّ ٱلْقَوْلُ عَلَى ٱلْكَٰفِرِينَ", "en": "To warn whosoever liveth, and that the word may be fulfilled against the disbelievers."},
    {"n": 71, "ar": "أَوَلَمْ يَرَوْا۟ أَنَّا خَلَقْنَا لَهُم مِّمَّا عَمِلَتْ أَيْدِينَآ أَنْعَٰمًۭا فَهُمْ لَهَا مَٰلِكُونَ", "en": "Have they not seen how We have created for them of Our handiwork the cattle, so that they are their owners,"},
    {"n": 72, "ar": "وَذَلَّلْنَٰهَا لَهُمْ فَمِنْهَا رَكُوبُهُمْ وَمِنْهَا يَأْكُلُونَ", "en": "And have subdued them unto them, so that some of them they have for riding, some for food?"},
    {"n": 73, "ar": "وَلَهُمْ فِيهَا مَنَٰفِعُ وَمَشَارِبُ ۖ أَفَلَا يَشْكُرُونَ", "en": "Benefits and (divers) drinks have they from them. Will they not then give thanks?"},
    {"n": 74, "ar": "وَٱتَّخَذُوا۟ مِن دُونِ ٱللَّهِ ءَالِهَةًۭ لَّعَلَّهُمْ يُنصَرُونَ", "en": "And they have taken (other) gods beside Allah, in order that they may be helped."},
    {"n": 75, "ar": "لَا يَسْتَطِيعُونَ نَصْرَهُمْ وَهُمْ لَهُمْ جُندٌۭ مُّحْضَرُونَ", "en": "It is not in their power to help them; but they (the worshippers) are unto them a host in arms."},
    {"n": 76, "ar": "فَلَا يَحْزُنكَ قَوْلُهُمْ ۘ إِنَّا نَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ", "en": "So let not their speech grieve thee (O Muhammad). Lo! We know what they conceal and what proclaim."},
    {"n": 77, "ar": "أَوَلَمْ يَرَ ٱلْإِنسَٰنُ أَنَّا خَلَقْنَٰهُ مِن نُّطْفَةٍۢ فَإِذَا هُوَ خَصِيمٌۭ مُّبِينٌۭ", "en": "Hath not man seen that We have created him from a drop of seed? Yet lo! he is an open opponent."},
    {"n": 78, "ar": "وَضَرَبَ لَنَا مَثَلًۭا وَنَسِىَ خَلْقَهُۥ ۖ قَالَ مَن يُحْىِ ٱلْعِظَٰمَ وَهِىَ رَمِيمٌۭ", "en": "And he hath coined for Us a similitude, and hath forgotten the fact of his creation, saying: Who will revive these bones when they have rotted away?"},
    {"n": 79, "ar": "قُلْ يُحْيِيهَا ٱلَّذِىٓ أَنشَأَهَآ أَوَّلَ مَرَّةٍۢ ۖ وَهُوَ بِكُلِّ خَلْقٍ عَلِيمٌ", "en": "Say: He will revive them Who produced them at the first, for He is Knower of every creation,"},
    {"n": 80, "ar": "ٱلَّذِى جَعَلَ لَكُم مِّنَ ٱلشَّجَرِ ٱلْأَخْضَرِ نَارًۭا فَإِذَآ أَنتُم مِّنْهُ تُوقِدُونَ", "en": "Who hath appointed for you fire from the green tree, and behold! ye kindle from it."},
    {"n": 81, "ar": "أَوَلَيْسَ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ بِقَٰدِرٍ عَلَىٰٓ أَن يَخْلُقَ مِثْلَهُم ۚ بَلَىٰ وَهُوَ ٱلْخَلَّٰقُ ٱلْعَلِيمُ", "en": "Is not He Who created the heavens and the earth Able to create the like of them? Aye, that He is! for He is the All-Wise Creator,"},
    {"n": 82, "ar": "إِنَّمَآ أَمْرُهُۥٓ إِذَآ أَرَادَ شَيْـًٔا أَن يَقُولَ لَهُۥ كُن فَيَكُونُ", "en": "But His command, when He intendeth a thing, is only that He saith unto it: Be! and it is."},
    {"n": 83, "ar": "فَسُبْحَٰنَ ٱلَّذِى بِيَدِهِۦ مَلَكُوتُ كُلِّ شَىْءٍۢ وَإِلَيْهِ تُرْجَعُونَ", "en": "Therefor Glory be to Him in Whose hand is the dominion over all things! Unto Him ye will be brought back."}
  ]
};
